<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Hzs.Common\Hzs.Common.csproj" />
    <ProjectReference Include="..\Hzs.Generated\Hzs.Generated.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ValveResourceFormat" Version="20.0.6980" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
