// GENERATED by tools/gen_sheets.py - do not edit by hand
namespace Hzs.Generated;

/// <summary>A sheet cell: either a constant (JSON text) or a binding resolved from a game install.</summary>
public readonly record struct Binding(string? Source, string? Key, string? ConstJson)
{
    public static Binding From(string source, string key) => new(source, key, null);
    public static Binding Const(string json) => new(null, null, json);
    public static readonly Binding Unset = new(null, null, null);
    public bool IsBound => Source is not null;
}
