// GENERATED by tools/gen_sheets.py from sheets/machine_attacks.json - do not edit by hand
namespace Hzs.Generated;

public sealed record MachineAttacksRow(string Id, string DisplayName, string Kind, string Direction, double RangeMinM, double RangeMaxM, double Damage, double ArmorRatio, double WindupS, double ActiveS, double CooldownS, double ProjectileSpeedMps, double KnockbackMps, string Pose);

public static class MachineAttacksSheet
{
    public static readonly MachineAttacksRow WatcherBite = new("watcher_bite", "Bite", "melee", "front", 0.0, 2.5, 20.0, 1.2, 0.4, 0.2, 1.6, 0.0, 2.0, "lunge_bite");
    public static readonly MachineAttacksRow WatcherTailSweep = new("watcher_tail_sweep", "Tail sweep", "melee", "any", 0.0, 3.5, 15.0, 1.2, 0.5, 0.3, 3.0, 0.0, 4.0, "tail_sweep");
    public static readonly MachineAttacksRow WatcherEyeBolt = new("watcher_eye_bolt", "Eye bolt", "ranged", "front", 6.0, 30.0, 12.0, 1.0, 0.8, 0.1, 2.5, 40.0, 1.0, "eye_charge");
    public static readonly MachineAttacksRow StriderRearKick = new("strider_rear_kick", "Rear kick", "melee", "rear", 0.0, 3.0, 35.0, 1.2, 0.35, 0.2, 2.0, 0.0, 6.0, "rear_kick");
    public static readonly MachineAttacksRow StriderCharge = new("strider_charge", "Charge", "charge", "front", 6.0, 25.0, 30.0, 1.2, 0.6, 1.5, 6.0, 0.0, 8.0, "charge");
    public static readonly MachineAttacksRow GrazerRotorSweep = new("grazer_rotor_sweep", "Rotor sweep", "melee", "front", 0.0, 3.5, 25.0, 1.2, 0.6, 0.4, 3.0, 0.0, 5.0, "rotor_sweep");
    public static readonly MachineAttacksRow GrazerRam = new("grazer_ram", "Ram", "charge", "front", 4.0, 20.0, 20.0, 1.2, 0.5, 1.2, 5.0, 0.0, 6.0, "ram");
    public static readonly System.Collections.Generic.IReadOnlyList<MachineAttacksRow> All = new[] { WatcherBite, WatcherTailSweep, WatcherEyeBolt, StriderRearKick, StriderCharge, GrazerRotorSweep, GrazerRam };
}
