// GENERATED by tools/gen_sheets.py from sheets/site_map.json - do not edit by hand
namespace Hzs.Generated;

public sealed record SiteMapRow(string Id, string Kind, string HzdName, string Machine, bool Populate, double CountMult, string Notes);

public static class SiteMapSheet
{
    public static readonly SiteMapRow GroupResourcegatheringherd = new("group:resourcegatheringherd", "group", "resourcegatheringherd", "grazer", true, 1.0, "grazer herd site: acquisition herd");
    public static readonly SiteMapRow GroupRghCollectors = new("group:rgh_collectors", "group", "rgh_collectors", "grazer", true, 1.0, "herd collectors: acquisition herd members");
    public static readonly SiteMapRow GroupRghResourcegathering = new("group:rgh_resourcegathering", "group", "rgh_resourcegathering", "grazer", true, 1.0, "herd gathering: acquisition herd members");
    public static readonly SiteMapRow GroupRghCollectorsprotection = new("group:rgh_collectorsprotection", "group", "rgh_collectorsprotection", "watcher", true, 1.0, "herd guards: Watchers guarding a herd");
    public static readonly SiteMapRow GroupRecongroup = new("group:recongroup", "group", "recongroup", "watcher", true, 1.0, "patrol: patrol / recon");
    public static readonly SiteMapRow GroupTransportgroup = new("group:transportgroup", "group", "transportgroup", "strider", true, 1.0, "convoy: transport convoy");
    public static readonly SiteMapRow GroupCargocarriergroup = new("group:cargocarriergroup", "group", "cargocarriergroup", "strider", true, 1.0, "cargo carriers: transport convoy");
    public static readonly SiteMapRow GroupScavengegroup = new("group:scavengegroup", "group", "scavengegroup", "watcher", true, 1.0, "scavengers: scavenger pack");
    public static readonly SiteMapRow GroupScavengecollectors = new("group:scavengecollectors", "group", "scavengecollectors", "watcher", true, 1.0, "scavenger collectors: scavenger pack");
    public static readonly SiteMapRow GroupSectordefence = new("group:sectordefence", "group", "sectordefence", "watcher", true, 1.0, "sector defence: guarded area");
    public static readonly SiteMapRow TypeScout = new("type:scout", "type", "scout", "watcher", true, 1.0, "Watcher (verified); same count");
    public static readonly SiteMapRow TypeLaserscout = new("type:laserscout", "type", "laserscout", "watcher", true, 1.0, "Redeye Watcher (verified); same count");
    public static readonly SiteMapRow TypeAntelope = new("type:antelope", "type", "antelope", "grazer", true, 1.0, "Lancehorn (verified); same count");
    public static readonly SiteMapRow TypeHorse = new("type:horse", "type", "horse", "strider", true, 1.0, "Strider (verified); same count");
    public static readonly SiteMapRow TypeHarvester = new("type:harvester", "type", "harvester", "grazer", true, 1.0, "Grazer (verified); same count");
    public static readonly SiteMapRow TypeLonghorn = new("type:longhorn", "type", "longhorn", "grazer", true, 1.0, "Broadhead (verified); same count");
    public static readonly SiteMapRow TypeBison = new("type:bison", "type", "bison", "strider", true, 1.0, "Trampler (verified); same count");
    public static readonly SiteMapRow TypeGoat = new("type:goat", "type", "goat", "strider", true, 1.0, "Charger (verified); same count");
    public static readonly SiteMapRow TypeHyena = new("type:hyena", "type", "hyena", "watcher", true, 1.0, "Scrapper (verified); same count");
    public static readonly SiteMapRow TypeRaptor = new("type:raptor", "type", "raptor", "watcher", true, 1.5, "Thunderjaw (verified); predator: more v1 machines");
    public static readonly SiteMapRow TypeDirewolf = new("type:direwolf", "type", "direwolf", "watcher", true, 1.5, "Sawtooth (verified); predator: more v1 machines");
    public static readonly SiteMapRow TypeGreywolf = new("type:greywolf", "type", "greywolf", "watcher", true, 1.5, "Ravager (verified); predator: more v1 machines");
    public static readonly SiteMapRow TypeStalker = new("type:stalker", "type", "stalker", "watcher", true, 1.5, "Stalker (verified); predator: more v1 machines");
    public static readonly SiteMapRow TypeLonglegbird = new("type:longlegbird", "type", "longlegbird", "watcher", true, 1.0, "Longleg (verified); same count");
    public static readonly SiteMapRow TypeGlider = new("type:glider", "type", "glider", "watcher", true, 1.0, "Glinthawk (verified); same count");
    public static readonly SiteMapRow TypeThunderhawk = new("type:thunderhawk", "type", "thunderhawk", "watcher", true, 2.0, "Stormbird (verified); predator: more v1 machines");
    public static readonly SiteMapRow TypeBeachlizard = new("type:beachlizard", "type", "beachlizard", "watcher", true, 1.0, "Snapmaw (verified); same count");
    public static readonly SiteMapRow TypeCrab = new("type:crab", "type", "crab", "strider", true, 1.0, "Shell-Walker (verified); same count");
    public static readonly SiteMapRow TypeCargorhino = new("type:cargorhino", "type", "cargorhino", "strider", true, 1.0, "Behemoth (verified); same count");
    public static readonly SiteMapRow TypeSpraybot = new("type:spraybot", "type", "spraybot", "strider", true, 1.0, "Fire/Freeze Bellowback (verified); same count");
    public static readonly SiteMapRow TypeMole = new("type:mole", "type", "mole", "watcher", true, 1.0, "Rockbreaker (verified); same count");
    public static readonly SiteMapRow TypeHackbot = new("type:hackbot", "type", "hackbot", "watcher", true, 1.5, "likely Corruptor (entity has no display name); predator: more v1 machines");
    public static readonly SiteMapRow TypeWarrobot = new("type:warrobot", "type", "warrobot", "watcher", true, 2.0, "likely Thunderjaw; predator: more v1 machines");
    public static readonly SiteMapRow TypeGiraffe = new("type:giraffe", "type", "giraffe", "watcher", false, 0.0, "likely Tallneck; landmark machine, never hostile: not populated");
    public static readonly System.Collections.Generic.IReadOnlyList<SiteMapRow> All = new[] { GroupResourcegatheringherd, GroupRghCollectors, GroupRghResourcegathering, GroupRghCollectorsprotection, GroupRecongroup, GroupTransportgroup, GroupCargocarriergroup, GroupScavengegroup, GroupScavengecollectors, GroupSectordefence, TypeScout, TypeLaserscout, TypeAntelope, TypeHorse, TypeHarvester, TypeLonghorn, TypeBison, TypeGoat, TypeHyena, TypeRaptor, TypeDirewolf, TypeGreywolf, TypeStalker, TypeLonglegbird, TypeGlider, TypeThunderhawk, TypeBeachlizard, TypeCrab, TypeCargorhino, TypeSpraybot, TypeMole, TypeHackbot, TypeWarrobot, TypeGiraffe };
}
