"""Generate code from the design sheets. Each sheet row becomes one struct:

  sheets/<name>.json -> game/generated/<name>.gd                  (GDScript: one const Dictionary per row + ROWS)
                     -> converter/src/Hzs.Generated/<Name>.cs    (C#: one record instance per row + All)

Bindings ({"cs2": "..."} / {"hzd": "..."}) are emitted as Binding values; the converter resolves them from the
player's install and the game reads the resolved numbers from the cache. Run: python tools/gen_sheets.py
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHEETS = os.path.join(ROOT, "sheets")
GD_OUT = os.path.join(ROOT, "game", "generated")
CS_OUT = os.path.join(ROOT, "converter", "src", "Hzs.Generated")

HEADER = "GENERATED by tools/gen_sheets.py from sheets/{0}.json - do not edit by hand"


def pascal(name):
    parts = re.split(r"[^0-9A-Za-z]+", str(name))
    out = "".join(p[:1].upper() + p[1:] for p in parts if p)
    if not out or out[0].isdigit():
        out = "R" + out
    return out


def gd_ident(name):
    s = re.sub(r"[^0-9A-Za-z_]", "_", str(name)).upper()
    return ("R_" + s) if s[:1].isdigit() else s


def gd_value(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return json.dumps(v, ensure_ascii=False)
    if isinstance(v, list):
        return "[" + ", ".join(gd_value(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{" + ", ".join(f"{json.dumps(str(k))}: {gd_value(x)}" for k, x in v.items()) + "}"
    raise TypeError(type(v))


def cs_type(spec):
    t = spec.get("type", "string")
    if spec.get("from") in ("cs2", "hzd"):
        return "Binding"
    return {
        "number": "double", "int": "int", "bool": "bool", "string": "string", "enum": "string", "ref": "string",
    }.get(t, "string")  # list/object/other -> JSON text


def cs_literal(v, spec):
    t = cs_type(spec)
    if t == "Binding":
        if isinstance(v, dict) and ("cs2" in v or "hzd" in v):
            src = "cs2" if "cs2" in v else "hzd"
            key = v[src] if isinstance(v[src], str) else json.dumps(v[src], ensure_ascii=False)
            return f"Binding.From({json.dumps(src)}, {json.dumps(key, ensure_ascii=False)})"
        if v is None:
            return "Binding.Unset"
        return f"Binding.Const({json.dumps(json.dumps(v, ensure_ascii=False), ensure_ascii=False)})"
    if v is None:
        return "default!"
    if t == "double":
        return repr(float(v)) if isinstance(v, (int, float)) else "double.NaN"
    if t == "int":
        return str(int(v)) if isinstance(v, (int, float)) else "0"
    if t == "bool":
        return "true" if v is True else "false"
    if t == "string" and spec.get("type") in ("list", "object") or not isinstance(v, str):
        return json.dumps(json.dumps(v, ensure_ascii=False), ensure_ascii=False)
    return json.dumps(v, ensure_ascii=False)


def gen_gd(sname, sheet):
    key = sheet.get("key", "id")
    cols = sheet.get("columns", {})
    lines = [f"# {HEADER.format(sname)}", f"class_name {pascal(sname)}Sheet", "extends RefCounted", ""]
    lines.append(f"const SHEET := {json.dumps(sname)}")
    lines.append(f"const KEY := {json.dumps(key)}")
    lines.append("const COLUMNS := " + gd_value({c: {k: v for k, v in s.items() if k != 'desc'} for c, s in cols.items()}))
    lines.append("")
    names = []
    for row in sheet.get("rows", []):
        ident = gd_ident(row.get(key))
        names.append((row.get(key), ident))
        body = {c: row.get(c) for c in cols}
        lines.append(f"const {ident} := {gd_value(body)}")
    lines.append("")
    lines.append("const ROWS := {" + ", ".join(f"{json.dumps(str(k))}: {i}" for k, i in names) + "}")
    lines.append("")
    lines.append("static func row(id: String) -> Dictionary:")
    lines.append("\treturn ROWS.get(id, {})")
    lines.append("")
    lines.append("static func ids() -> Array:")
    lines.append("\treturn ROWS.keys()")
    return "\n".join(lines) + "\n"


def gen_cs(sname, sheet):
    key = sheet.get("key", "id")
    cols = sheet.get("columns", {})
    rec = pascal(sname) + "Row"
    props = [f"{cs_type(spec)} {pascal(c)}" for c, spec in cols.items()]
    lines = [f"// {HEADER.format(sname)}", "namespace Hzs.Generated;", "",
             f"public sealed record {rec}(" + ", ".join(props) + ");", "",
             f"public static class {pascal(sname)}Sheet", "{"]
    names = []
    for row in sheet.get("rows", []):
        ident = pascal(row.get(key))
        names.append(ident)
        args = ", ".join(cs_literal(row.get(c), spec) for c, spec in cols.items())
        lines.append(f"    public static readonly {rec} {ident} = new({args});")
    lines.append(f"    public static readonly System.Collections.Generic.IReadOnlyList<{rec}> All = new[] {{ " + ", ".join(names) + " };")
    lines.append("}")
    return "\n".join(lines) + "\n"


BINDING_CS = """// GENERATED by tools/gen_sheets.py - do not edit by hand
namespace Hzs.Generated;

/// <summary>A sheet cell: either a constant (JSON text) or a binding resolved from a game install.</summary>
public readonly record struct Binding(string? Source, string? Key, string? ConstJson)
{
    public static Binding From(string source, string key) => new(source, key, null);
    public static Binding Const(string json) => new(null, null, json);
    public static readonly Binding Unset = new(null, null, null);
    public bool IsBound => Source is not null;
}
"""


def main():
    if not os.path.isdir(SHEETS):
        print("no sheets/ folder")
        return 1
    os.makedirs(GD_OUT, exist_ok=True)
    os.makedirs(CS_OUT, exist_ok=True)
    n = 0
    for name in sorted(os.listdir(SHEETS)):
        if not name.endswith(".json"):
            continue
        with open(os.path.join(SHEETS, name), encoding="utf-8") as f:
            sheet = json.load(f)
        sname = sheet.get("sheet", name[:-5])
        with open(os.path.join(GD_OUT, f"{sname}.gd"), "w", encoding="utf-8", newline="\n") as f:
            f.write(gen_gd(sname, sheet))
        with open(os.path.join(CS_OUT, f"{pascal(sname)}.cs"), "w", encoding="utf-8", newline="\n") as f:
            f.write(gen_cs(sname, sheet))
        n += 1
        print(f"{sname}: {len(sheet.get('rows', []))} rows")
    with open(os.path.join(CS_OUT, "Binding.cs"), "w", encoding="utf-8", newline="\n") as f:
        f.write(BINDING_CS)
    print(f"generated {n} sheet(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
